# -------------------判断基础任务是否失败的超时参数-----------------------
# 如果状态机切换为起飞状态，超过 takeoff_wait_s 仍旧处于takeoff状态，认为起飞失败
takeoff_wait_s: 30 
# 如果状态机切换为降落状态，超过 land_wait_s 仍旧处于land状态，认为降落失败
land_wait_s: 30
# ps:由于返航是通过先移动到返航的位置下降，因此返航的超时时间为降落时间+位置控制超时时间组合而成

# -------------------当任务超时触发的应对措施-----------------------
# 起飞阶段超时的应对措施： 0:继续等待 1:切换为悬停模式 2:切换为降落模式 3:切换为紧急降落模式
takeoff_timeout_operate: 2
# 降落阶段超时的应对措施： 0:继续等待 1:切换为px4.autoland降落模式 2:切换为紧急降落模式 3:切换为紧急锁桨，电机停转
land_timeout_operate: 0
